title: Rahul Mahale
description: /var/log/rahul
author: Rahul Mahale
logo: /static/img/avatar.png
github: https://github.com/RahulMahale
about: Linux Guy

#baseurl: "https://codeasashu.github.io/hcz-jekyll-blog"
#url: "https://codeasashu.github.io/hcz-jekyll-blog"

disqus_shortname: slashrahul
google_analytics: UA-72862926-1

share:
  twitter_username: Rahul_Mahale
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
